laurel_sprout: fingerprint: drop in-kernel handling of changes
This commit is a squash of the following commits:

laurel_sprout: drop in-kernel handling of changes

laurel_sprout: fingerprint: adopted for our laurel_sprout

laurel_sprout: add missing libs

laurel_sprout: added missing `set` method to BiometricsFingerprint

device/xiaomi/laurel_sprout/fingerprint/BiometricsFingerprint.cpp:430:5: error: use of undeclared identifier 'set'
    set(DISPPARAM_PATH, DISPPARAM_HBM_FOD_ON);
    ^
device/xiaomi/laurel_sprout/fingerprint/BiometricsFingerprint.cpp:432:5: error: use of undeclared identifier 'set'
    set(FOD_STATUS_PATH, FOD_STATUS_ON);
    ^
device/xiaomi/laurel_sprout/fingerprint/BiometricsFingerprint.cpp:439:5: error: use of undeclared identifier 'set'
    set(DISPPARAM_PATH, DISPPARAM_HBM_FOD_OFF);
    ^
device/xiaomi/laurel_sprout/fingerprint/BiometricsFingerprint.cpp:441:5: error: use of undeclared identifier 'set'
    set(FOD_STATUS_PATH, FOD_STATUS_OFF);

Co-authored-by: PowerX-NOT <pugalg100@gmail.com>
Co-authored-by: aleeeee1 <pace.alessandro05@protonmail.com>
Signed-off-by: Skyblueborb <tomaszborbely0710@gmail.com>